#!/bin/bash

YEAR=${2:-2020}
DAY=$1
SESSION=$(grep SESSION .env | cut -d '=' -f2)

mkdir -p $YEAR/$DAY
cp -n boilerplate.go $YEAR/$DAY/main.go
open http://adventofcode.com/${YEAR}/day/${DAY}
wget --header "Cookie: session=$SESSION" -O $YEAR/$DAY/input http://adventofcode.com/${YEAR}/day/${DAY}/input